### PR TITLE
CSV delimiter autodetect method

### PR DESCRIPTION
**Pull request by fazzinipierluigi**

### CODE REVIEW

**Comment by nyamsprod** [comment]
@fazzinipierluigi thanks for the PR. 

I would like to understand the added value of adding this method versus using the documented function ? 

https://csv.thephpleague.com/9.0/connections/controls/#detecting-the-delimiter-character

**Comment by fazzinipierluigi** [comment]
in my opinion the method is more consistent than it is in the class and does not return a statistical analysis of all the inserted delimiters but if one is found this is set, making it easier and more immediate to use.
It's just a practical motivation. =)

**Comment by nyamsprod** [comment]
Understood but your implementation may lead to false positive and incorrect results. This is why this function which once was in the public API of the Reader class was removed from it. To clearly state that the response should be taken with a grain of salt.

**Comment by nyamsprod** [comment]
@fazzinipierluigi   I will reject your PR on the ground that this is an old public API method previously called `detectDelimiterList` that was deprecated because of the false sense of certitude that it gives to users.

**Pull request closed without merging**
