### PR TITLE
Feature/move tests

### PR DESCRIPTION
**Pull request by nyamsprod**
Removing the tests directory

### CODE REVIEW

**Comment by guilliamxavier** [comment]
Gosh, why? https://www.reddit.com/r/PHP/comments/2jzp6k/i_dont_need_your_tests_in_my_production/

**Comment by nyamsprod** [comment]
the tests won't end up it production they are removed from the git repo using the `.gitattributes` you are safe 😉

**Comment by nyamsprod** [comment]
As for the why the main selling point is maintenance.

**Comment by guilliamxavier** [comment]
Thanks for replying.

> the tests won't end up it production they are removed from the git repo using the `.gitattributes` you are safe 😉

Ah, I hadn't seen the followup https://github.com/thephpleague/csv/commit/3adc302d192d9d4e8b0bef7962d83172f1ca013a, fine.

> As for the why the main selling point is maintenance.

Well, I wouldn't buy it, but hey, your project 🙊

**Pull request merged**
