### PR TITLE
Fix phpdoc

### PR DESCRIPTION
**Pull request by ghobaty**
_The things I do to get my IDE to stop complaining..._

### CODE REVIEW

**Comment by nyamsprod** [comment]
Nice catch I prefer declaring the import on top of the class. Once this is done I'll gladly merge your PR. Thanks for the contribution

**Comment by cafferata** [comment]
>*Nice catch I prefer declaring the import on top of the class.*

@nyamsprod, the import is already on top of the class.
*https://github.com/thephpleague/csv/blob/master/src/Reader.php#L19*

@ghobaty, when you are into fixing the DocBlocks, there are more missing/wrong DocBlocks in de codebase (11x). @ghobaty would you like to fix this? Or shall I do this?

```diff
    /**
     * Determine the CSV record header.
     *
     * @param int $offset
     *
+    * @return string[]
     * @throws Exception If the header offset is set and no record is found or is the empty array
     */
    protected function setHeader(int $offset): array
    {
```

```diff
    /**
     * Returns the row at a given offset.
     *
+    * @param int $offset
     *
     * @return array|false
     */
    protected function seekRow(int $offset)
    {
```

**Comment by ghobaty** [comment]
@cafferata please feel free to!

**Comment by nyamsprod** [comment]
@cafferata there are not missing. If the argument is defined using PHP7 parameter type hinting they are not reported again using docblock. It enables better maintenance :wink

**Comment by cafferata** [comment]
@nyamsprod I partially agree with you. Yes it can be a choice to omit the DocBlocks in connection with the PHP 7 parameter type hinting. However, the existing DocBlocks have multiple `@param` hints that are not always complete/correct.

Examples:

```diff
   /**
     * Retuns the CSV document as a Generator of string chunk.
     *
-    * @param int $length number of bytes read
-    *
     * @throws Exception if the number of bytes is lesser than 1
     */
    public function chunk(int $length): Generator
    {
```
*\League\Csv\AbstractCsv::chunk*

```diff
   /**
     * New instance.
     *
-    * @param string   $escape        escape character to escape each CSV formula field
-    * @param string[] $special_chars additional spreadsheet formula starting characters
-    *
     */
    public function __construct(string $escape = "\t", array $special_chars = [])
    {
```
*\League\Csv\EscapeFormula::__construct*

In addition, there is a small problem in the example above. The default value for parameters with a class type can only be `NULL`.

```json
php: >=7.0.10
```
*https://github.com/thephpleague/csv/blob/master/composer.json#L24*

**Comment by nyamsprod** [comment]
@cafferata maybe create a separate thread issue for you suggestion as this current PR was already accepted and I prefer having one issue per thread if possible. you can even propose a PR and we can discuss it there .

**Pull request merged**
