### PR TITLE
Output File on Disk

### PR DESCRIPTION
**Pull request by Gabriellpweb**
Added method outputFile to save csv on disk.

### Targeted release version
dev-master

### PR Impact
It was implemented based on master. Must change $this->getCsvDocument() to $this->getIterator() to work on 8.* releases.

### CODE REVIEW

**Comment by nyamsprod** [comment]
@Gabriellpweb Thanks for the PR but I don't get the reasoning for this feature ? The file is already saved to the disk when using the Writer class ? What's the added value ?

**Comment by Gabriellpweb** [comment]
I need the file on disk, but the output method only provides download. So I've implemented a method to only save in the disk.

**Comment by nyamsprod** [comment]
But if you use the Writer class the file *is* saved to the disk

```php
<?php

require 'vendor/autoload.php';

$csv = Writer::createFromFileObject(new SplFileObject('path/to/file.csv', 'w'));
$csv->insertAll($data_to_insert);
$csv = null;
```
if you look into `path/to/file.csv` the data is inserted. So I don't understand your PR.

**Comment by Gabriellpweb** [comment]
You're right! Sorry =s! Closing!

**Pull request closed without merging**
