### PR TITLE
Update ResultSet.php

### PR DESCRIPTION
**Pull request by netbull**
actually return the json encoded

### CODE REVIEW

**Comment by nyamsprod** [comment]
What's the reasoning behind this PR? Not only is it BC breaking but also I fail to understand it's need 🤔

**Comment by netbull** [comment]
was the method suppose to return a json encoded string as the method name states? now it returns plain array.. or probably i'm missing something :/

**Comment by nyamsprod** [comment]
Indeed you're missing the fact that the class is correctly implementing a PHP interface 😉

**Comment by netbull** [comment]
i'm such an idiot... sorry to bother..

**Pull request closed without merging**
